
version: "3.8"
services:

  keyvault:
    build:
      context: .
      dockerfile: Dockerfile
    image: keyvault:latest
    ports:
      - "443:443"
    networks:
      - host
    volumes: 
      - ${HOST_DATA_DIR:-keyvault}/:/usr/local/keyvault/
    environment: 
      - KV_CERT_DIR=/usr/local/keyvault/
      - KV_DB_PATH=/usr/local/keyvault/vault.db
      - GIN_MODE=release
      - KV_MODE=production
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  host:
