
version: "3.8"
services:

  keyvault:
    build:
      context: .
      dockerfile: Dockerfile
    image: keyvault:latest
    ports:
      - "443:443"
    networks:
      - host
    volumes: 
      - ${HOST_DATA_DIR:-keyvault}/etc:/usr/local/keyvault/etc
      - ${HOST_DATA_DIR:-keyvault}/certs:/usr/local/keyvault/certs
      - ${HOST_DATA_DIR:-keyvault}/db:/usr/local/keyvault/db
    environment: 
      - CERT_CONF_DIR=/usr/local/keyvault/etc
      - CERT_DIR=/usr/local/keyvault/certs
      - DB_PATH=/usr/local/keyvault/db/vault.db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  host:
